[package]
name = "springbok"
version = "0.3.10"
description = "GUI image optimizer build on tauri"
authors = ["tree.xie@outlook.com"]
license = "Apache License 2.0"
repository = "https://github.com/vicanso/springbok"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "springbok_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
tauri = { version = "2.2.2", features = ["protocol-asset"] }
tauri-plugin-shell = "2.2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
imageoptimize = "0.1.8"
snafu = "0.8.5"
tokio = { version = "1.43.0", default-features = false, features = ["fs"] }
blake3 = "1.5.5"
tauri-plugin-os = "2.2.0"
once_cell = "1.20.2"
glob = "0.3.2"
tauri-plugin-dialog = "2.2.0"
base64 = "0.22.1"
walkdir = "2.5.0"

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true        # Enables link-time-optimizations.
opt-level = "s"   # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort"   # Higher performance by disabling panic handlers.
strip = true      # Ensures debug symbols are removed.
