import { Button, VerticalBox, ListView, HorizontalBox, CheckBox, SpinBox } from "std-widgets.slint";

export global Config  {
    in-out property <bool> support-png: true;
    in-out property <int> png-quality: 0;

    in-out property <bool> support-jpeg: true;
    in-out property <int> jpeg-quality: 0;

    in-out property <bool> support-webp: true;
    in-out property <int> webp-quality: 0;

    in-out property <bool> support-avif: true;
    in-out property <int> avif-quality: 0;

    in-out property <string> save_path;
}

component TableView inherits Rectangle {
    in property <[string]> columns;
    in property <[[string]]> values;
    in property <bool> processing;
    in property <string> processing-tips;
    in property <string> select-btn-text;
    callback show-open-dialog;

    VerticalBox {
        HorizontalLayout {
            width: parent.width - 28px;
            HorizontalLayout{
                width: 40px;
                Text {
                    text: " ";
                }
                Rectangle {
                    width: 1px;
                    background: gray;
                }
            }
            HorizontalLayout{
                padding-left: 10px;
                Text {
                    text: @tr("File");
                }
                Rectangle {
                    width: 1px;
                    background: gray;
                }
            }
            HorizontalLayout{
                width: 80px;
                Text {
                    horizontal-alignment: center;
                    text: @tr("Size");
                }
                Rectangle {
                    width: 1px;
                    background: gray;
                }
            }
            HorizontalLayout{
                width: 80px;
                Text {
                    horizontal-alignment: center;
                    text: @tr("Savings");
                }
                Rectangle {
                    width: 1px;
                    background: gray;
                }
            }
            HorizontalLayout{
                width: 80px;
                // listview 存在滚动条
                padding-right: 15px;
                Text {
                    horizontal-alignment: center;
                    text: @tr("Dssim");
                }
            }
        }
        ListView {
            for item in values : Rectangle { 
                background: item[0] == "even" ? root.background.brighter(30%) : root.background;
                HorizontalLayout {
                    padding-bottom: 8px;
                    padding-top: 8px;
                    Text {
                        width: 40px;
                        horizontal-alignment: center;
                        text: item[1];
                    }
                    HorizontalLayout{
                        padding-left: 8px;
                        Text {
                            text: item[2];
                        }
                    }
                    HorizontalLayout {
                        width: 80px;
                        Text {
                            horizontal-alignment: center;
                            text: item[3];
                        }
                    }
                    HorizontalLayout {
                        width: 80px;
                        Text {
                            horizontal-alignment: center;
                            text: item[4];
                        }
                    }
                    HorizontalLayout {
                        width: 80px;
                        Text {
                            horizontal-alignment: center;
                            text: item[5];
                        }
                    }
                }
            }
        }
        HorizontalLayout {
            Button {
                text: processing ? select-btn-text : "+";
                clicked => { show-open-dialog(); }
            }
            HorizontalLayout {
                padding-left: 15px;
                CheckBox {
                    width: 80px;
                    text: "JPEG";
                    checked: Config.support-jpeg;
                    toggled => {
                        Config.support-jpeg = self.checked;
                    }
                }
                SpinBox { 
                    enabled: Config.support-jpeg;
                    value: Config.jpeg-quality;
                    minimum: 60;
                    maximum: 100;
                    edited => {
                        Config.jpeg-quality = self.value;
                    }
                    width: 90px;
                }
            }
            HorizontalLayout {
                padding-left: 15px;
                CheckBox {
                    width: 75px;
                    text: "PNG";
                    checked: Config.support-png;
                    toggled => {
                        Config.support-png = self.checked;
                    }
                }
                SpinBox { 
                    enabled: Config.support-png;
                    value: Config.png-quality;
                    minimum: 60;
                    maximum: 100;
                    edited => {
                        Config.png-quality = self.value;
                    }
                    width: 90px;
                }
            }
            HorizontalLayout {
                padding-left: 15px;
                CheckBox {
                    width: 80px;
                    text: "WebP";
                    checked: Config.support-webp;
                    toggled => {
                        Config.support-webp = self.checked;
                    }
                }
                SpinBox { 
                    enabled: Config.support-webp;
                    value: Config.webp-quality;
                    minimum: 60;
                    maximum: 100;
                    edited => {
                        Config.webp-quality = self.value;
                    }
                    width: 90px;
                }
            }
            HorizontalLayout {
                padding-left: 15px;
                CheckBox {
                    width: 75px;
                    text: "AVIF";
                    checked: Config.support-avif;
                    toggled => {
                        Config.support-avif = self.checked;
                    }
                }
                SpinBox { 
                    enabled: Config.support-avif;
                    value: Config.avif-quality;
                    minimum: 60;
                    maximum: 100;
                    edited => {
                        Config.avif-quality = self.value;
                    }
                    width: 90px;
                }
            }
        }
    }
}

export component AppWindow inherits Window {
    preferred-width: 818px;
    preferred-height: 600px;
    callback show-open-dialog;
    title: @tr("Image Converter");
    in property <[string]> columns;
    in property <[[string]]> values;
    in property <bool> processing;
    in property <string> processing-tips;
    in property <string> select-btn-text;
    default-font-size: 13px;
    default-font-weight: 500;
    TableView {
        show-open-dialog => { show-open-dialog(); }
        columns: columns;
        values: values;
        processing: processing;
        background: root.background;
        processing-tips: processing-tips;
        select-btn-text: select-btn-text;
    }
}
