import { Button, VerticalBox, ListView, GridBox, ScrollView, HorizontalBox } from "std-widgets.slint";

component TableView inherits Rectangle {
    in property <[string]> columns;
    in property <[[string]]> values;

    VerticalBox {
        HorizontalLayout {
            width: parent.width - 28px;
            HorizontalLayout{
                width: 40px;
                Text {
                    text: " ";
                }
                Rectangle {
                    width: 1px;
                    background: gray;
                }
            }
            HorizontalLayout{
                padding-left: 10px;
                Text {
                    text: @tr("File");
                }
                Rectangle {
                    width: 1px;
                    background: gray;
                }
            }
            HorizontalLayout{
                width: 80px;
                padding-left: 10px;
                Text {
                    text: @tr("Size");
                }
                Rectangle {
                    width: 1px;
                    background: gray;
                }
            }
            HorizontalLayout{
                padding-left: 10px;
                width: 80px;
                Text {
                    text: @tr("Savings");
                }
                Rectangle {
                    width: 1px;
                    background: gray;
                }
            }
            HorizontalLayout{
                width: 80px;
                padding-left: 10px;
                Text {
                    text: @tr("Dssim");
                }
            }
        }
        ListView {
            for item in values : HorizontalLayout {
                padding-bottom: 10px;
                Text {
                    width: 40px;
                    text: item[0];
                }
                Text {
                    padding-left: 10px;
                    text: item[1];
                }
                Text {
                    padding-left: 10px;
                    width: 80px;
                    text: item[2];
                }
                Text {
                    padding-left: 10px;
                    width: 80px;
                    text: item[3];
                }
                Text {
                    padding-left: 10px;
                    width: 80px;
                    text: item[4];
                }
            }
        }
    }
}

export component AppWindow inherits Window {
    preferred-width: 700px;
    preferred-height: 500px;
    title: @tr("Image Converter");
    in property <[string]> columns;
    in property <[[string]]> values;
    TableView {
        columns: root.columns;
        values: root.values;
    }
}
